"""Remove currency field from transactions

Revision ID: 0d11acde8703
Revises: a66cac8ff7c4
Create Date: 2025-07-31 16:30:14.409488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d11acde8703'
down_revision: Union[str, None] = 'a66cac8ff7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    # ### end Alembic commands ###