"""Remove total_amount column from transactions

Revision ID: a22655edf37d
Revises: 0d11acde8703
Create Date: 2025-07-31 17:50:58.202335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22655edf37d'
down_revision: Union[str, None] = '0d11acde8703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'total_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('total_amount', sa.NUMERIC(precision=20, scale=8), autoincrement=False, nullable=False))
    # ### end Alembic commands ###