"""Initial migration

Revision ID: a66cac8ff7c4
Revises: 
Create Date: 2025-07-27 06:26:16.947595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66cac8ff7c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_exchange_rates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_currency', sa.String(length=3), nullable=False),
    sa.Column('to_currency', sa.String(length=3), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'date', name='uq_currency_pair_date')
    )
    op.create_index(op.f('ix_historical_exchange_rates_date'), 'historical_exchange_rates', ['date'], unique=False)
    op.create_index(op.f('ix_historical_exchange_rates_from_currency'), 'historical_exchange_rates', ['from_currency'], unique=False)
    op.create_index(op.f('ix_historical_exchange_rates_id'), 'historical_exchange_rates', ['id'], unique=False)
    op.create_index(op.f('ix_historical_exchange_rates_to_currency'), 'historical_exchange_rates', ['to_currency'], unique=False)
    op.create_table('historical_stock_prices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('adjusted_close', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume', sa.Numeric(precision=20, scale=0), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_symbol_date')
    )
    op.create_index(op.f('ix_historical_stock_prices_date'), 'historical_stock_prices', ['date'], unique=False)
    op.create_index(op.f('ix_historical_stock_prices_id'), 'historical_stock_prices', ['id'], unique=False)
    op.create_index(op.f('ix_historical_stock_prices_symbol'), 'historical_stock_prices', ['symbol'], unique=False)
    op.create_table('stock_metadata',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_stock_metadata_symbol'), 'stock_metadata', ['symbol'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('pension_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pension_accounts_id'), 'pension_accounts', ['id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('additional_currencies', sa.JSON(), nullable=True),
    sa.Column('retirement_goal', sa.JSON(), nullable=True),
    sa.Column('ynab_budget_id', sa.String(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('current_quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_cost_per_share', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_id'), 'holdings', ['id'], unique=False)
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    op.create_table('pension_value_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('contributions', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['pension_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pension_value_entries_id'), 'pension_value_entries', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('holding_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'SPLIT', 'TRANSFER_IN', 'TRANSFER_OUT', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fees', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('average_cost_per_share_at_transaction', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_pension_value_entries_id'), table_name='pension_value_entries')
    op.drop_table('pension_value_entries')
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_pension_accounts_id'), table_name='pension_accounts')
    op.drop_table('pension_accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_metadata_symbol'), table_name='stock_metadata')
    op.drop_table('stock_metadata')
    op.drop_index(op.f('ix_historical_stock_prices_symbol'), table_name='historical_stock_prices')
    op.drop_index(op.f('ix_historical_stock_prices_id'), table_name='historical_stock_prices')
    op.drop_index(op.f('ix_historical_stock_prices_date'), table_name='historical_stock_prices')
    op.drop_table('historical_stock_prices')
    op.drop_index(op.f('ix_historical_exchange_rates_to_currency'), table_name='historical_exchange_rates')
    op.drop_index(op.f('ix_historical_exchange_rates_id'), table_name='historical_exchange_rates')
    op.drop_index(op.f('ix_historical_exchange_rates_from_currency'), table_name='historical_exchange_rates')
    op.drop_index(op.f('ix_historical_exchange_rates_date'), table_name='historical_exchange_rates')
    op.drop_table('historical_exchange_rates')
    # ### end Alembic commands ###